env:
  global:
    - CC_TEST_REPORTER_ID=6dcbe8a085cfeb89e6776aafcaf5843c0a36007df567c0e4f401b88753ba188e

before_install:

  # System dependencies
  - sudo apt-get update
  - sudo apt-get install -y p7zip-full

  # Code Climate setup
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

language: "node_js"

node_js: 
  - "node"

script:
  - npm run coverage

after_script: 

  # Send coverage to Coveralls.io
  - npm run coveralls
  
  # Send coverage to Code Climate
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
