# Test against the latest version of this Node.js version
environment:
  nodejs_version: ''

# Install scripts. (runs after repo cloning)
install:
  # Download 7z Binary to _mock for testing $path special option
  - curl -fsS https://www.7-zip.org/a/7z1805-x64.exe -o"7z.exe"
  - copy "7z.exe" "./test/_mock/Seven Zip"
  - dir test
  - 7z # Display 7z version and help
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run test-ci

# Don't actually build.
build: off